### PR TITLE
New file

### PR DESCRIPTION
**Pull request by JanErikHoel**
## File

File from Trimble Quadri for sprint 2
Think we have covered:

- Spatial breakdown structure
- Classification 
- Project Global Positioning - Scenario A

## Covered Concept Templates - Usages Included

*Please list all Usages you have implemented.*

1. 

## Miscellaneous

*Please use this area to convey anything else.*

### CODE REVIEW

**Comment by JanErikHoel** [comment]
Hmmm...

In our IFC conversion system in Quadri, ifcClassificationReference is automatically created to make the connection between ifcClassification and ifcRelAssociatesClassification:

#29 = IFCCLASSIFICATION('Svensk Byggtjanst', '', $, 'CoClass', '', $, $);
#30 = IFCCLASSIFICATIONREFERENCE('', '', '', #29, '', $);
#31 = IFCRELASSOCIATESCLASSIFICATION('0nSdb46q14iwUy1guYKw9Q', #6, 'CoClass', $, (#19, #23), **#30**);

When ifcClassificationReference is applied this way, then the classification shows nicely on the Classification tab in BIMVision e.g. BUT your validation test fails.

When I read the specification for the 6th and last attribute for ifcRelAssociatesClassification, I find that this is 
IfcClassificationSelect which again can be either IfcClassification or IfcClassificationReference.

Isn't your validation to strict here?

**Comment by SergejMuhic** [comment]
We are checking this template =>https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/link/project-classification-information.htm

This is the assignment of an `IfcClassification` to an `IfcProject`. It is not too strict, it just checks an exact usage of a template. You cannot classify a project (assign an `IfcClassificationReference` to it), a project has a complete `IfcClassification` assigned which is the metadata to which the `IfcClassificationReference` occurences "belong".

**Comment by JanErikHoel** [comment]
OK - I can remove the #23 ifcGeotechnicalStratum from the ifcRelAssociatesClassification statement, but the question is then:
How do I specify the classification for the ifcGeotechnicalStratum?
Do I make another ifcRelAssociatesClassification with a new unique GUID that refers to both the ifcGeotechnicalStratum and the ifcClassificationReference as shown below as #32?

I know this is out of scope for this test, but very good for us to know because we will fix our parsing code according to how we now learn that this should be set up.

#29 = IFCCLASSIFICATION('Svensk Byggtjanst', '', $, 'CoClass', '', $, $);
#30 = IFCCLASSIFICATIONREFERENCE('', '', '', #29, '', $);
#31 = IFCRELASSOCIATESCLASSIFICATION('0nSdb46q14iwUy1guYKw9Q', #6, 'CoClass', $, (#19), #29);
#32 = IFCRELASSOCIATESCLASSIFICATION('0nSdb46q14iwUy1guYKw9P', #6, 'CoClass', $, (#23), #30);

**Comment by SergejMuhic** [comment]
> OK - I can remove the #23 ifcGeotechnicalStratum from the ifcRelAssociatesClassification statement, but the question is then:
> How do I specify the classification for the ifcGeotechnicalStratum?

We will be doing that in sprint 3. The template that is then being used for this part is [this](https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/link/classification-association.htm).



> Do I make another ifcRelAssociatesClassification with a new unique GUID that refers to both the ifcGeotechnicalStratum and the ifcClassificationReference as shown below as #32?

Yes, this seems okay. You are missing the second part of the template though. `IfcClassification` and `IfcClassificationReference` connection:
image
Filling the IfcClassification.HasReference inverse is resolved from the serialized ⬇️ 

Or in the `Classification association` template this part:
image
IfcClassificationReference.ReferencedSource

**Comment by Artemis-kc** [comment]
Hello,
I am following up here as the files for the Geotechnics are highly related to Jan Eriks work. I need to do a follow up with him internally and answer some questions, before I upload any file.

**Review by pjanck — COMMENTED** [review]
Question regarding the coordinates: the file states that the CRS used is ETRS89 / NTM zone 10 (EPSG:5110) and the coordinates' values in `IFCCARTESIANPOINTLIST3D` are somewhere around ~(100k, 1200k) with translation values (0,0,0) in `IFCMAPCONVERSION`. Are you certain that the model is in local engineering coordinates and not in map coordinates? If the former is the case, `IfcMapConversion` is correctly used. In the case of the latter, I suggest using `IfcRigidOperation`.

**Comment by JanErikHoel** [comment]
NTM zone 10 is not distorted (a meter is a meter), so engineering coordinates are the same as the map coordinates.
Infrastructure software in Norway handle these large coordinates
Is it anything wrong in our setup of mapping coordinates based on this information?

**Comment by JanErikHoel** [comment]
I try to really understand your comment in the meeting, Stefan , about using ifcRigidOperation instead of ifcMapConversion - because you suggested to use this INSTEAD  and not in addition - right?

This is my file:
#15 = IFCGEOMETRICREPRESENTATIONCONTEXT('3D', 'Model', 3, 1.E-5, #13, #16);
#16 = IFCDIRECTION((-0., 1., 0.));
#17 = IFCPROJECTEDCRS('EPSG:5110', 'ETRS89 / NTM zone 10', $, '5776:NN54 height', $, $, #7);
_#18 = IFCMAPCONVERSION(#15, #17, 0., 0., 0., $, $, $, $, $);_
#18 = IFCRIGIDOPERATION(#15,#17,0.0,0.0,0.0);

So the idea is to change the first #18 with the latter #18?
Change from the red marked mapping to the green marked translation in your image as I copied in below?

image

But the question is then when we use another coordinate system like UTM33 in the export e.g. In our UI the user can change to another CRS when exporting and we don't want to make different coding depending in the coordinate system is distorted or not. Can we use ifcRigidOperation even for this case?

And another question: 
In our UI we have the possibility define a translation (used mainly to get smaller coordinate values if the receiving software can't handle large values). In our resulting IFC-file, it looks like this for a translation of 100 in both X- and Y-direction (we use ifcAxis2Placement3D:
#13 = IFCAXIS2PLACEMENT3D(#14, $, $);
#14 = IFCCARTESIANPOINT((100., 100., 0.));
#15 = IFCGEOMETRICREPRESENTATIONCONTEXT('3D', 'Model', 3, 1.E-5, #13, #16);
#16 = IFCDIRECTION((-0., 1., 0.));

Is this correct?
What is the difference between this and ifcRigidOperation? Is it so that ifcAxis2Placement3D is for engineering coordinates while ifcRigidOperation is for mapping coordinates?

**Comment by SergejMuhic** [comment]
> So the idea is to change the first #18 with the latter #18?

Correct. If the rest of the file is in projected coordinates this would be the way to go.

`IfcRigidOperation` implies that there is no distortion in the dataset i. e. IFC file coordinates and these are placed in the `IfcProjectedCRS` and not a local engineering coordinate system.

> But the question is then when we use another coordinate system like UTM33 in the export e.g. In our UI the user can change to another CRS when exporting and we don't want to make different coding depending in the coordinate system is distorted or not. Can we use ifcRigidOperation even for this case?

In this case, `IfcRigidOperation` should probably be used as well. You did not say whether the coordinates in the dataset are in the `IfcProjectedCRS` that is referenced.

`IfcMapConversion` shall be used when the coordinates in the IFC dataset are in local engineering coordinates and have to be transformed into projected coordinates before construction commences.

**Comment by JanErikHoel** [comment]
Thanks a lot for your answers!

But my last question is still unsolved:
"What is the difference between this and ifcRigidOperation? Is it so that ifcAxis2Placement3D is for engineering coordinates while ifcRigidOperation is for mapping coordinates?"

**Comment by SergejMuhic** [comment]
> `IfcRigidOperation` implies that there is no distortion in the dataset i. e. IFC file coordinates and these are placed in the `IfcProjectedCRS` and not a local engineering coordinate system.

This is where I was answering the difference between `IfcRigidOperation` and `IfcMapConversion`. If `IfcRigidOperation` is used it implies that the entire dataset is in projected coordinates, otherwise, (`IfcMapConversion`) as the name implies the coordinates in the IFC are converted / transformed to local engineering.

**Pull request closed without merging**
