### PR TITLE
Attempt to adress issue #197

### PR DESCRIPTION
**Pull request by larswik**
Used updated LandXML=>IFC converter from Peter Bonsma for IFC Alignment.
Attempted to adress issue #197.

Also added the file directly converted from LandXML (TESTSWE_UT_LP4.ifc).

### CODE REVIEW

**Comment by larswik** [comment]
@pjanck : When you have the time: Can you check why the checks failed?

**Comment by SergejMuhic** [comment]
Apparently no report is being generated.

I can tell you in the meantime that `IfcGeometricRepresentationContext`.`HasCoordinateOperation` cannot have two operations. The uploaded file has both an `IfcMapConversion` and an `IfcRigidOpeartion`.

```
#250 IfcGeometricRepresentationContext failing: The field HasCoordinateOperation must be a string or array type with a maximum length of '1'.
```

**Comment by larswik** [comment]
> Apparently no report is being generated.
> 
> "Error: No files were found with the provided path: D:\a\IFC-Tunnel-Deployment\IFC-Tunnel-Deployment\results."
> 
> My assumption is that Serialization errors are the problem. The `IfcCurveMeasureSelect` change to `IfcLengthMeasure` instead of `IfcNonNegativeLengthMeasure` has not yet been injected into IFC4X4.
> 
> I can tell you in the meantime that `IfcGeometricRepresentationContext`.`HasCoordinateOperation` cannot have two operations. The uploaded file has both an `IfcMapConversion` and an `IfcRigidOpeartion`.
> 
> ```
> #250 IfcGeometricRepresentationContext failing: The field HasCoordinateOperation must be a string or array type with a maximum length of '1'.
> ```

Oops. Don't know how that happened. Maybe too much tags along when cloning in the alignment data in the file? Need to check that.

**Comment by larswik** [comment]
> > Apparently no report is being generated.
> > "Error: No files were found with the provided path: D:\a\IFC-Tunnel-Deployment\IFC-Tunnel-Deployment\results."
> > My assumption is that Serialization errors are the problem. The `IfcCurveMeasureSelect` change to `IfcLengthMeasure` instead of `IfcNonNegativeLengthMeasure` has not yet been injected into IFC4X4.
> > I can tell you in the meantime that `IfcGeometricRepresentationContext`.`HasCoordinateOperation` cannot have two operations. The uploaded file has both an `IfcMapConversion` and an `IfcRigidOpeartion`.
> > ```
> > #250 IfcGeometricRepresentationContext failing: The field HasCoordinateOperation must be a string or array type with a maximum length of '1'.
> > ```
> 
> Oops. Don't know how that happened. Maybe too much tags along when cloning in the alignment data in the file? Need to check that.

Tried to fix in [4bf23ab](https://github.com/bSI-InfraRoom/IFC-Tunnel-Deployment/pull/198/commits/4bf23abf7956253e98135338766462a352c72bca)

**Comment by pjanck** [comment]
@larswik It seems to work now.

**Comment by larswik** [comment]
I think that everything (with regards to sprint 2.1) for the 2.1 file should be ok now, except that the schema needs to be updated from 4.3 (i.e. IfcCurveMeasureSelect should use IfcLengthMeasure instead of IfcNonNegativeLengthMeasure).

**Pull request merged**
