### PR TITLE
fixing the documentation to allow for sectioned solid horizontal geom.

### LINKED ISSUE #185: Advanced SweptSolid as allowed geometry
Check 'Element's representation in Sprint 2.3' with uuid=23b70110-014e-4a7d-c0de-1fc10ce1deb1
There were 1 applicable and 0 not applicable IfcUndergroundExcavation(s) in the checked file.

2.3.2.ii) Correct Representation for Element: correct surfaic or volumentric type used. Following may be used: Body tesselation, Body Brep, Body Swept Solid, Surface Model, Voxel, Surface Tesselation

The following instances are failing:

#352, with GlobalId '3rVsqBF4j7UvaqqoBZaBIg'

In sprint 2.3 the allowed geometries does not allow Body Sectioned SolidHorizontal.
However in Sprint3.exc 1.i.a one of the allowed geometries is Body Sectioned SolidHorizontal

The current checker is complaining when I use Body Sectioned SolidHorizontal in Sprint 3.exc (RepresentationType = AdvancedSweptSolid).
The error message indicate it is due to the Sprint 2.3 limitation?

_Originally posted by @ivaroppen in https://github.com/bSI-InfraRoom/IFC-Tunnel-Deployment/issues/179#issuecomment-1722293961_

### PR DESCRIPTION
**Pull request by pjanck**
fixes #185

### CODE REVIEW

**Comment by pjanck** [comment]
Checker will be updated accordingly.

Additionally, the mistake regarding Containment of Underground Excavation noticed in #179 has been addressed as well.

**Comment by pjanck** [comment]
@ivaroppen Please review. (I cannot request your review through GitHub, somehow)

**Comment by ivaroppen** [comment]
lftm

**Comment by pjanck** [comment]
@ivaroppen Please give me 1 day to update the checker. I'll restart the action at your PR myself when updated and ping you.

**Pull request merged**
