### PR TITLE
Feature/sprint 3 exc

### PR DESCRIPTION
**Pull request by HannuLahtela**
## File

*Provide a short summary (3-5 lines):*
*For example, is it a new file, an update to an existing one?*
*Provide some bullet points about the content of the file, e.g. terrain model, tunnel structure, etc.*

## Covered Concept Templates - Usages Included

*Please list all Usages you have implemented.*

1. 

## Miscellaneous

*Please use this area to convey anything else.*

### CODE REVIEW

**Comment by pjanck** [comment]
@HannuLahtela Please sync from main, there is a change necessary to activate the checker. 

grafik

If you require assistance, please shoot me an email.

**Comment by HannuLahtela** [comment]
Done.
Ps. In the next two weeks or so, I'll be busy with another IFC project. So,
I won't join the online meetings then.

-Hannu-

Hannu Lahtela
Senior Software Engineer
------------------------------

Hatsinanpuisto 8A, 02600 Espoo
Finland
+358505701321 Mobile

***@***.***
www.trimble.com

**Comment by larswik** [comment]
Ping @pjanck. Can you check to see why the checker doesn't finish when you have some time?

**Comment by larswik** [comment]
@HannuLahtela : Can you please do the syncing of main for this branch as well (same as you did for #102)?

**Pull request merged**
