### PR TITLE
Sprint 3_Sys Distribution Port example

### PR DESCRIPTION
**Pull request by AdamMackellar12d**
Distribution Port example for 3_Sys.
Covered
- Port Connectivity
- Groups

Not covered
- Materials
- Control flow
- Spatial Containment
- Psets

### CODE REVIEW

**Comment by pjanck** [comment]
@AdamMackellar12d Please sync from main, there is a change necessary to activate the checker. 

grafik

If you require assistance, please shoot me an email.

**Comment by larswik** [comment]
- Regarding the ContextOfItems missing attribute, I think that the error is slightly misleading and that it actually concerns the 
  IfcShapeRepresentation at #288 which is reported below (IfcShapeRepresentation)
- Regarding "Georef parameters present": I think that it is the IfcProjectedCRS at #20 that should have either an "EPSG:" or a WKT in the  name attribute (attribute nr 1)
- Regarding "ConnectedFrom/ConnectedTo", I think that IfcDistributionPort #664 is connected two times (ConnectedFrom) and two times (ConnectedTo).
- IfcSystem: Components should be assigned using IfcRelAssignsToGroup

**Comment by pjanck** [comment]
@AdamMackellar12d As discussed today during the call, please ignore the message that `#338` is non-empty. I will amend the checker.

**Comment by pjanck** [comment]
> I will amend the checker.

Done. The results seem better now.

**Comment by pjanck** [comment]
Hint: `#814` should have `IFCBOOLEAN(.T.)` instead of `IFCBOOLEAN('.T.')`. Boolean values are not strings, rather they are enumerations :)

**Review by larswik — CHANGES_REQUESTED** [review]
- (Minor) Pset_DistributionPortTypePipe missing for IfcDistributionPort
- (Major) Use IfcRelAssignsToGroup and not IfcRelAggregates when grouping elements to an IfcDistributionSystem
- (Minor) IfcPipeSegment contained in IfcSite (and not IfcTunnel/IfcTunnelPart)
- (Minor) Pset_PipeSegmentTypeCommon missing for IfcPipeSegment
- (Major) IfcDistributionChamberElement(`#178`) and IfcPipeSegment(`#409`) contained directly in IfcProject which is not allowed (must be an IfcSpatialElement according to schema)

**Comment by pjanck** [comment]
As explained during the support call, we invite you to update the file in a new PR.

**Pull request merged**
