### PR TITLE
First attempt for Sprin2_1

### PR DESCRIPTION
**Pull request by JanErikHoel**
## File

Second try of sprint 2_2

## Covered Concept Templates - Usages Included

Think I've covered all aspects 

## Miscellaneous

*Please use this area to convey anything else.*

### CODE REVIEW

**Comment by JanErikHoel** [comment]
I'm afraid I now need some help to find out why the ifcProject and/or ifcGroup fails and why the ifcAlignmentHorizontal fails

**Comment by SergejMuhic** [comment]
> I'm afraid I now need some help to find out why the ifcProject and/or ifcGroup fails and why the ifcAlignmentHorizontal fails

Your #608 `IfcGroup` is not declared on `IfcProject`. It should be declared as in `IfcRelDeclares` on `IfcProject`. It should not be referenced in spatial structure. There is no concept template that would allow this. `IfcRelReferencedInSpatialStructure` had one partially documented usage that was never used consistently. It was to be used to reference `IfcCurtainWall` in `IfcBuildingStorey` if a facade stretched over one storey. 

A quick glance tells me that your `IfcAlignmenthorizontal` does not have a `CLOTHOID` segment.

**Comment by JanErikHoel** [comment]
Hurrayyy!!!

**Comment by JanErikHoel** [comment]
Thanks for SUPER-QUICK and very useful help Sergej!!

**Review by larswik — APPROVED** [review]
LFTM. I don't know of such a rule, but I think  that it would be cleaner if all uses of Project declaration were collected in one IfcRelDeclares. I didn't check the IfcCourse/IfcGeoModel stuff.

**Comment by pjanck** [comment]
> all uses of Project declaration were collected in one IfcRelDeclares

I'm unsure if that would be correct - see [here](https://github.com/bSI-InfraRoom/IFC-Tunnel-Deployment/pull/113#issuecomment-1498540996).

**Comment by larswik** [comment]
> > all uses of Project declaration were collected in one IfcRelDeclares
> 
> I'm unsure if that would be correct - see [here](https://github.com/bSI-InfraRoom/IFC-Tunnel-Deployment/pull/113#issuecomment-1498540996).

I see the point for nesting, but fail to see the point for declarations.

**Comment by SergejMuhic** [comment]
> > all uses of Project declaration were collected in one IfcRelDeclares
> 
> I'm unsure if that would be correct - see [here](https://github.com/bSI-InfraRoom/IFC-Tunnel-Deployment/pull/113#issuecomment-1498540996).

Project Declaration is one usage though ... 😬

**Comment by pjanck** [comment]
As said, I was unsure and I stand corrected! Thank you for clearing it out for me! :)

**Review by pjanck — APPROVED** [review]
lftm

The file has a lot more content than required - this approval only covers the concepts as part of Sprint 2.1 and its prerequisites. It may be that the file will fail future checks and will need amendment.

**Pull request merged**
