### PR TITLE
Bever Control Sprint 3.exc

### PR DESCRIPTION
**Pull request by ivaroppen**
## File

A draft for Sprint 3.exc

## Covered Concept Templates - Usages Included

The defined consept templates and usages should be included in this draft.

### CODE REVIEW

**Comment by pjanck** [comment]
@ivaroppen Please sync from main, there is a change necessary to activate the checker. 

grafik

If you require assistance, please shoot me an email.

**Comment by ivaroppen** [comment]
Sorry, I need some help with this:

Check 'Underground excavation in Sprint 3.exc' with uuid=3e71c130-014e-4a7d-c0de-1fc10ce1deb1
3.e.Exc.1.iv) No spatial containment for underground excavation

The following instances are failing:

#352, with GlobalId '3rVsqBF4j7UvaqqoBZaBIg'

Could you please point me in the direction of what I am doing wrong?

**Comment by pjanck** [comment]
> 3.e.Exc.1.iv) No spatial containment for underground excavation

`#352` is contained through `IfcRelContainedInSpatialStructure`, although this is forbidden. It is sufficient to connect it through `IfcRelVoidsElements`.

> The current checker is complaining when I use Body Sectioned SolidHorizontal in Sprint 3.exc (RepresentationType = AdvancedSweptSolid).

Your interpretation is correct. We will update the checker - I'll open an issue for this.

**Comment by pjanck** [comment]
> I'll double check the checker as well.

It was the checker as well. I'll update it together with #185 fixes.

**Comment by pjanck** [comment]
> It was the checker as well.

I've managed to update the checker - thank you for pointing out the errors in its implementation!

**Review by larswik — COMMENTED** [review]
Great job with an interesting model! We could merge this with a few comments:
- IfcTunnelTypicalSection should be contained and not aggregated
- It seems as if there are two IfcGeoScienceModel (one, PHYSICALDISTRIBUTIONMODEL, aggregating the other, NOTDEFINED)
- The geometric representation in this case could be mad emore efficient since all profiles has an equal number of vertices. One IfcSectionedSolidHorizontal with four profiles would do. However, the current representation works. It would be interesting with the widened part having a different number of vertices in the profile. In that case, e.g. an IfcFacetedBrep would be needed in the widening part. It would be interesting though to add guiding curves to the excavation body representation :-)
- IfcElementAssembly missing PredefinedType=.ARCH.
- IfcArchElement has PredefinedType USERDEFINED (maybe a software library issue?)
- IfcArchElement=>Material missing PSet_MaterialConcrete
- In the IfcBuiltSystem/TUNNEL_SUPPORT, both the IfcElementAssembly and the IfcArchElement (which is decomposing the IfcBuiltsystem) is included 
- The IfcArchElementType and IfcArchElement are not associated. Maybe that's teh intention?

**Comment by ivaroppen** [comment]
> IfcArchElement has PredefinedType USERDEFINED (maybe a software library issue?)

Yes, I think it’s a library issue. 
I created the `IfcTunnelTypicalSection` in my code. 
However, fixing the `IfcArchElement` require me to do a too deep intervention into the library code....

>The geometric representation in this case could be made more efficient <

Agree, however, I did not fix it this time.

>The IfcArchElementType and IfcArchElement are not associated. Maybe that's the intention?

Sorry, did not fix in this time.


The remaining points in the review should be fixed in this version…

**Comment by SergejMuhic** [comment]
> > IfcArchElement has PredefinedType USERDEFINED (maybe a software library issue?)
> 
> Yes, I think it’s a library issue. I created the `IfcTunnelTypicalSection` in my code. However, fixing the `IfcArchElement` require me to do a too deep intervention into the library code....

The workaround is quite nice though. I can offer a re-serialization with IFC Reactor to make it better but it would modify your header FILE_NAME content to a different processor. Let me know whether you would like me to do that.

It is turning out to be quite the "beacon file".

**Comment by ivaroppen** [comment]
I found a way to override the library. It is in the pull request now.
However, if you like: Please go ahead re-serialize, it is always interesting to see the master solution

**Comment by ivaroppen** [comment]
Comment on the Nov 16th support calls: 
Please see #164 for an explanation on the guidelines. 
As agreed, the guidelines are not lines in 3D space. 
They describe how a single parameter varies along the peg number axis (offset y, offset z and radius)...

**Comment by SergejMuhic** [comment]
We should create a usage for it. We have the resolution documented in issues https://github.com/bSI-InfraRoom/IFC-Specification/issues/118 and https://github.com/bSI-InfraRoom/IFC-Specification/issues/648.

I have created an issue to resolve the applicable entities:
https://github.com/bSI-InfraRoom/IFC-Specification/issues/730

**Pull request merged**
