### PR TITLE
ACCA_IfcTunnel_Sprint_1_1

### PR DESCRIPTION
**Pull request by michelangelo-acca**
## File

This is the IFC file produced from ACCA software for the Sprint 1_1.

It contains: 

- Project 
- UM
- Context 
- An empty Group

## Covered Concept Templates - Usages Included

The covered concept templates are:

1. Project Unit Assignment
2. Project Representation Context
3. Project Declaration

### CODE REVIEW

**Comment by michelangelo-acca** [comment]
No idea where the check is failing...can you please manually check to see where it is failing?

**Comment by pjanck** [comment]
The reason is probably #25 - please be patient, while the checker gets updated :)

**Comment by michelangelo-acca** [comment]
Oh I see, thank you!

**Comment by SergejMuhic** [comment]
Apologies @michelangelo-acca . Unfortunately, the documentation was a bit ambiguous and naturally we setup the checker with the wrong configuration.

**Comment by michelangelo-acca** [comment]
No problem!

**Review by pjanck — APPROVED** [review]
lftm

**Review by larswik — APPROVED** [review]

**Pull request merged**
