### PR TITLE
Create RoadAlignment.ifc

### PR DESCRIPTION
**Pull request by JanErikHoel**
## File

First try

## Covered Concept Templates - Usages Included

Hopefully all usages from Sprint1

### CODE REVIEW

**Comment by pjanck** [comment]
@JanErikHoel Please merge the latest commits from this repository into your branch and push. It should restart the action with the new fixed checker.

**Comment by pjanck** [comment]
Breadcrumbs: #31.

**Comment by JanErikHoel** [comment]
@pjanck waiting for approval

**Comment by pjanck** [comment]
I think you still need to merge the bSI-InfraRoom/main branch into your branch - if you need help, we can have a quick call.

**Comment by JanErikHoel** [comment]
Hmm - I added these two lines to the end of the file to declare an actor, but it didn't seem to help.
#279 = IFCRELDECLARES('2DAvEupIz0HQr73cMacwtY', $, $, $, #19, (#280));
#280 = IFCACTOR('2DAvEupIz0HQr73cMacwtX', $, $, $, $, #4);

I'm afraid I need some more advice to what is missing/wrong here so that I can instruct the developers to fix this correctly

**Comment by SergejMuhic** [comment]
You have two files with errors:
rev2:
1. has no IfcRelDeclares (that is your Project Declaration fail)
2. `#15 = IFCGEOMETRICREPRESENTATIONCONTEXT('Model', '3D', 3, 1.E-5, #13, #16);` - values 'Model' and '3D' are switched

rev3
has 1. fixed
2. remains

**Comment by JanErikHoel** [comment]
GREAT!!!!

**Comment by SergejMuhic** [comment]
[Super green](https://www.youtube.com/watch?v=_HZB0lkunWA).

**Review by pjanck — APPROVED** [review]
The file has a lot more content than required - this approval only covers the concepts as part of Sprint 1.1. It may be that the file will fail future checks and will need amendment.

**Pull request merged**
